# Generated by Django 5.1.6 on 2025-02-27 12:04
from django.db import migrations

def create_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Менеджеры')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.RunPython(create_manager_group),
    ]
